### ISSUE TITLE
Migration en trop

### ISSUE THREAD

**Issue by leahpar** [PierreThiollent/Mini-CMS-with-Symfony#2]
La migration `Version20200213210220.php` est de trop, elle créée une table User inutilisée.

En plus avec un type JSON disponible en MySQL >= 5.7 alors que je suis en 5.6 (comme encore beaucoup de monde).
D'où l'intérêt de préciser la version dans le `.env` et/ou dans `config/packages/doctrine.yaml` pour que le `php bin/console make:migration` utilise les bon types disponibles (en l'occurrence un simple string pour MySQL <5.7).

**Comment by PierreThiollent** [comment]
En effet j'ai commit une migration en trop car j'ai ajouté le bundle sécurity afin de bloquer l'admin aux utilisateurs non authentifiés. Mais je n'ai pas encore terminé cette fonctionnalité.
